### ISSUE TITLE
Firefox version

### ISSUE THREAD

**Issue by gagarine** [harsilspatel/moodle-downloader#16]
According to https://www.extensiontest.com the extension is compatible with Firefox without any change except 3 calls to `chrome.downloads.onDeterminingFilename` API in popup.js .

So when this bug land https://bugzilla.mozilla.org/show_bug.cgi?id=1245652 it should be a matter of packaging and uploading the extension on https://addons.mozilla.org/en-US/firefox/

**Comment by harsilspatel** [comment]
I don't think I'd be bothering adding firefox support. Happy to accept PRs thought!
