### ISSUE TITLE
Make it works on the main course page and use real link

### ISSUE THREAD

**Issue by gagarine** [harsilspatel/moodle-downloader#17]
Not all teacher activates the resource page. Trying to use "download them all" plugin to not works because link are not pointing directly to the PDF and some Javasdcript it's used to open the right link when you click (seriously, WTF).

![Screenshot 2020-01-02 at 18 12 22](https://user-images.githubusercontent.com/164074/71680876-8ac39900-2d8b-11ea-9091-c93464135e5e.png)

Therefor, It would be great of the MoodleDownloader work on the main course page.

It can also fix the link in the same time by using proper links. Instead of having one links:

![Screenshot 2020-01-02 at 18 14 39](https://user-images.githubusercontent.com/164074/71681097-189f8400-2d8c-11ea-879b-4a4a0d82286a.png)

We can have one links that point directly to the PDF (the link opened with the "onclick" event) and one links (info) that point to the moodle document page (https://moodle.taltech.ee/mod/resource/view.php?id=XXX)

![Screenshot 2020-01-02 at 18 16 49](https://user-images.githubusercontent.com/164074/71681093-16d5c080-2d8c-11ea-8f54-4ef2b77e0ae9.png)

**Comment by harsilspatel** [comment]
Hey Simon,

Firstly, I'm terribly sorry for the late reply. Secondly, this looks like a fairly straightforward task, do you want to give it a go and create a PR? It'll be easier for you to test on your Moodle since mine doesn't have the said configuration!

Thanks for raising the issue!:D

Regards,
Harsil

**Comment by gagarine** [comment]
Sure I will give it a go.
