### ISSUE TITLE
Accented characters are replaced by spaces

### ISSUE THREAD

**Issue by joachimBrindeau** [harsilspatel/moodle-downloader#22]
Hello,

I just have an encoding issue with the folder creation.
Accented characters are replaced by spaces.
[picture](https://i.ibb.co/n3RLsrp/Capture.png)

Thank you for your work, great tool !

**Comment by harsilspatel** [comment]
Hey @joachimBrindeau,

Thanks so much for raising the issue. Please update to the latest version of the extension (v.1.5.0) and it should be working. I'll close the issue but if there's anything that isn't working as expected, feel free to raise another one.

Stay safe and don't forget to wash hands! :D

Regards,
H
