### ISSUE TITLE
Global variables in last commit

### ISSUE THREAD

**Issue by kmaltcev** [harsilspatel/moodle-downloader#25]
Hi there :)
First of all, I'd like to say a big thank you for your work.
I've found your extension in chrome store, but I'm not studying at your university, so I needed to fix some problems related to our university moodle and make it works also with Hebrew :)
But also I've found some bug at your code btw, when you trying to open extension window twice, on the second try you get this error:

> background.js:1 Uncaught SyntaxError: Identifier 'sesskey' has already been declared at VM24948 background.js:1

I'm not really into JS so I made some search on google and found a solution to around entire code with { }, and it fixed that.

**Comment by harsilspatel** [comment]
Hi @kmChrysalis,

Although it shouldn't have been the case given `sesskey` was defined as a variable (as opposed to a constant). Nevertheless, I've changed it's scope and hopefully that'll fix related issues. I've published an updated version (v1.5.1) in the Chrome Web Store, however it's pending to a review, but you can download the latest extension [here](https://github.com/harsilspatel/moodle-downloader/releases/latest).

Thanks heaps for pointing it out and taking time to lookup the solution for me!! ^_^

Regards,
H

**Comment by kmaltcev** [comment]
You should probably change the scope of SUPPORTED_FILES variable too, the same issue with it.
