### ISSUE TITLE
Objects not listed

### ISSUE THREAD

**Issue by pablodz** [harsilspatel/moodle-downloader#27]
Objects not listed:
- mp4 files
- liked files
- drive files
- exe files

**Comment by harsilspatel** [comment]
Hi @ZurMaD,

There's no easy way for me to inspect the html and include those in the downloader. PRs are welcome :)

**Comment by pablodz** [comment]
I'll check for code of other mp4 files downloader chrome extensions. It's not necessary to code all. Some of them also have the ability to download from external video providers loom.us drive.google.com or other clouds.
