### ISSUE TITLE
Organize into folders not working

### ISSUE THREAD

**Issue by shifoc** [harsilspatel/moodle-downloader#28]

**Comment by harsilspatel** [comment]
Just tried the latest version (1.5.1.148) and it does seem to be working.

**Comment by shifoc** [comment]
![image](https://user-images.githubusercontent.com/32818143/92392808-8bd17500-f127-11ea-868e-ed96420739e5.png)
![image](https://user-images.githubusercontent.com/32818143/92392838-97bd3700-f127-11ea-80dc-6e103ec4a8c0.png)
isn't supposed to put them in folders by topic
