### ISSUE TITLE
Does not recognise files reliably

### ISSUE THREAD

**Issue by ehausen** [harsilspatel/moodle-downloader#3]
Hello,

This plugin has a very nice idea! I tried it out, but unfortunately it does not recognise files reliably. For me one course for example it only recognises PDF files, but not the excel files.

The problem seems to be the way you are trying to filter only files from all the links by looking for "File" in _instancename_:
https://github.com/harsilspatel/MoodleDownloader/blob/0882f38c7475a5b1a0ceeb509e37576e58935c19/src/background.js#L10-L12

But it turns out that all the download links do not have this _instancename_.

But I think all the uploaded files seem to have url of with **/resource/** in it: ex: `/moodle/mod/resource/view.php?id=12345`

links seem to have: `/moodle/mod/url/view.php?id=12345`
assignments: `/moodle/mod/assign/view.php?id=12345`

So maybe looking for **resource** in the URL would be more reliable.
BUT - I don't know if this url structure is the same in all the Moodle versions, or if it's standard or configurable etc.

**Comment by harsilspatel** [comment]
Hello ehausen,

Thankyou for raising the issue, I will definitely look into it and make it compatible with more files. I will try out your suggestion, thanks again!

**Comment by ehausen** [comment]
Maybe this is relevant. http://xref-diff.mukudu-dev.net/moodle26/_functions/set_docs_path.html
Not sure

**Comment by ehausen** [comment]
Hey! Just saw that file (resource?) links are inside an element that has classes 
`class="activity resource modtype_resource " `

Links seem to have 
`class="activity url modtype_url "`

Of course not sure if all _resources_ are always downloadable files

**Comment by harsilspatel** [comment]
> Hey! Just saw that file (resource?) links are inside an element that has classes
> `class="activity resource modtype_resource " `

You're correct! 😄
I think that'll do? I'll try it out, thanks!

**Comment by harsilspatel** [comment]
Could you please try out the [latest release](https://github.com/harsilspatel/MoodleDownloader/releases/tag/v1.4.3) and let me know if it is working as intended?

**Comment by ehausen** [comment]
Works for me now, at least this course and one other. Not sure of course if there are some situations where `modtype_resource` could be something else than downloadable file.

One thing though. Excel files display names in the list now miss 4 letters in the end (see image). 
![screen shot 2018-12-30 at 16 34 27](https://user-images.githubusercontent.com/6204129/50548251-1f178f00-0c52-11e9-906b-59cc31a3d18d.png)
It's of course because `.slice(0, -4)` in: https://github.com/harsilspatel/MoodleDownloader/blob/8fe70138d69c545744483e3d3b0d5c7466d0ce83/src/background.js#L12

**Comment by harsilspatel** [comment]
Fixed it! Thanks for all the issues you've raised @ehausen
