### ISSUE TITLE
University board hosted by moodle does not yield results

### ISSUE THREAD

**Issue by essentialols** [harsilspatel/moodle-downloader#31]
The UCSB message board (Gauchospace) is implemented by moodle but unfortunately, nothing appears when I'm on a course site. Is this expected? Can it be fixed? Thanks!

**Comment by harsilspatel** [comment]
Hi @essentialols, I can't say anything until I inspect how the elements are structured for your moodle. Happy to accepts PRs though :)

**Comment by essentialols** [comment]
Thanks for letting me know. I was looking into the downloader because I don't have much time right now... I'll take a look into a PR at some later point perhaps.
