### ISSUE TITLE
Can't recognize videos

### ISSUE THREAD

**Issue by Kreijstal** [harsilspatel/moodle-downloader#33]
There is a moodle course with around 50 videos, this extension of course doesn't go beyond the resources of page 1, so it can't find them and download them :(

**Comment by harsilspatel** [comment]
Hi @Kreijstal,
While it doesn't support downloading videos, the extension does support downloading resources from all the Resources page. If your course url is as so `https://lms.monash.edu/course/view.php?id=42395&section=13#13`, replacing `view` with `resources` and dropping the `section` param will get you there `https://lms.monash.edu/course/resources.php?id=42395`
I'll close this for now but feel free to reopen it should you have any further questions

**Comment by Kreijstal** [comment]
that's ok https://github.com/marcelreppi/moodle-buddy can download videos, that's great!

**Comment by harsilspatel** [comment]
It looks good! Didn't know it was a thing, thanks for pointing it out :)
