### ISSUE TITLE
Stops working with locked files

### ISSUE THREAD

**Issue by LapisLazulis** [harsilspatel/moodle-downloader#4]
Hey, been trying your extension, really great one!
There's one problem, when one course has one file locked (even 1 in 300 files in a course) the extension outputs 0 recognized files
If it'd be possible to fix it that'd be cool thanks ^^

**Comment by harsilspatel** [comment]
Oh, not sure what locked files are. But sure I'll take a look at it :)

**Comment by LapisLazulis** [comment]
Sorry I can be super unclear ^^
they're files that you can set to be locked after a specific date, like for example a file not being available to be opened/downloaded after a set date (or manually lock it from downloading/viewing)

**Comment by harsilspatel** [comment]
Ah right, that makes sense. I'll take a look into it as soon as possible, thank you for reporting ^_^

**Comment by harsilspatel** [comment]
Mind trying out the latest v.1.4.5 release? @LapisLazulis

**Comment by LapisLazulis** [comment]
Works perfectly, thanks for fixing it so fast!
